version: '3.8'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/tyresehaliburton
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:newerjeans@db:5432/postgres2
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newerjeans
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
