"""Add games_played to AssistLeader

Revision ID: 1b1772b42693
Revises: 3f292baf2e48
Create Date: 2024-01-29 23:38:18.429009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1772b42693'
down_revision = '3f292baf2e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assist_leader', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_played', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('turnovers', sa.Numeric(precision=5, scale=3), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Numeric(precision=5, scale=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assist_leader', schema=None) as batch_op:
        batch_op.drop_column('points')
        batch_op.drop_column('turnovers')
        batch_op.drop_column('games_played')

    # ### end Alembic commands ###
