"""Initial migration.

Revision ID: 2094fc2b8cf5
Revises: def8fdb16ffa
Create Date: 2024-02-08 23:21:50.376624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2094fc2b8cf5'
down_revision = 'def8fdb16ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('assist_leader', sa.Boolean(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('assists', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('points', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('season_stats')
    # ### end Alembic commands ###
