"""Initial migration.

Revision ID: 22469868036b
Revises: 2094fc2b8cf5
Create Date: 2024-02-08 23:54:08.239578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22469868036b'
down_revision = '2094fc2b8cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('assist_leader', sa.Boolean(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('assists', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('points', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'player', ['player_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('season_stats')
    op.drop_table('season')
    op.drop_table('player')
    # ### end Alembic commands ###
