"""Updated migration for gamelogs

Revision ID: 44e1872ac7d3
Revises: e9078df9813c
Create Date: 2024-02-09 01:23:55.947090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e1872ac7d3'
down_revision = 'e9078df9813c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_stats_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('matchup', sa.String(), nullable=False),
    sa.Column('wl', sa.String(length=1), nullable=True),
    sa.Column('min', sa.Float(), nullable=False),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('fg3m', sa.Integer(), nullable=True),
    sa.Column('fg3a', sa.Integer(), nullable=True),
    sa.Column('fg3_pct', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Integer(), nullable=True),
    sa.Column('dreb', sa.Integer(), nullable=True),
    sa.Column('reb', sa.Integer(), nullable=True),
    sa.Column('ast', sa.Integer(), nullable=True),
    sa.Column('stl', sa.Integer(), nullable=True),
    sa.Column('blk', sa.Integer(), nullable=True),
    sa.Column('tov', sa.Integer(), nullable=True),
    sa.Column('pf', sa.Integer(), nullable=True),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_stats_id'], ['season_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_log')
    # ### end Alembic commands ###
