"""Updated migration for season stats

Revision ID: 95684fd178a8
Revises: 
Create Date: 2024-02-11 23:32:12.064276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95684fd178a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('assist_leader', sa.Boolean(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('ast', sa.Float(), nullable=True),
    sa.Column('pts', sa.Float(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('fgm', sa.Float(), nullable=True),
    sa.Column('fga', sa.Float(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('fg3m', sa.Float(), nullable=True),
    sa.Column('fg3a', sa.Float(), nullable=True),
    sa.Column('fg3_pct', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Float(), nullable=True),
    sa.Column('fta', sa.Float(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Float(), nullable=True),
    sa.Column('dreb', sa.Float(), nullable=True),
    sa.Column('reb', sa.Float(), nullable=True),
    sa.Column('stl', sa.Float(), nullable=True),
    sa.Column('blk', sa.Float(), nullable=True),
    sa.Column('tov', sa.Float(), nullable=True),
    sa.Column('pf', sa.Float(), nullable=True),
    sa.Column('eff', sa.Float(), nullable=True),
    sa.Column('ast_tov', sa.Float(), nullable=True),
    sa.Column('stl_tov', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_stats_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('matchup', sa.String(), nullable=False),
    sa.Column('wl', sa.String(length=1), nullable=True),
    sa.Column('min', sa.Float(), nullable=False),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('fg3m', sa.Integer(), nullable=True),
    sa.Column('fg3a', sa.Integer(), nullable=True),
    sa.Column('fg3_pct', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Integer(), nullable=True),
    sa.Column('dreb', sa.Integer(), nullable=True),
    sa.Column('reb', sa.Integer(), nullable=True),
    sa.Column('ast', sa.Integer(), nullable=True),
    sa.Column('stl', sa.Integer(), nullable=True),
    sa.Column('blk', sa.Integer(), nullable=True),
    sa.Column('tov', sa.Integer(), nullable=True),
    sa.Column('pf', sa.Integer(), nullable=True),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_stats_id'], ['season_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shotchart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_stats_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('x_coordinate', sa.Float(), nullable=False),
    sa.Column('y_coordinate', sa.Float(), nullable=False),
    sa.Column('shot_made', sa.Boolean(), nullable=False),
    sa.Column('grid_type', sa.String(), nullable=True),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_event_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('minutes_remaining', sa.Integer(), nullable=True),
    sa.Column('seconds_remaining', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('shot_type', sa.String(), nullable=True),
    sa.Column('shot_zone_basic', sa.String(), nullable=True),
    sa.Column('shot_zone_area', sa.String(), nullable=True),
    sa.Column('shot_zone_range', sa.String(), nullable=True),
    sa.Column('shot_distance', sa.Integer(), nullable=True),
    sa.Column('shot_attempted_flag', sa.Boolean(), nullable=True),
    sa.Column('htm', sa.String(), nullable=True),
    sa.Column('vtm', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['season_stats_id'], ['season_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shotchart')
    op.drop_table('game_log')
    op.drop_table('season_stats')
    op.drop_table('season')
    op.drop_table('player')
    # ### end Alembic commands ###
