"""connected

Revision ID: 9a8dd184dc7a
Revises: 
Create Date: 2024-01-30 00:15:43.371345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8dd184dc7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assist_leader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('assists', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('points', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.DateTime(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('turnovers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['assist_leader.player_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_log')
    op.drop_table('assist_leader')
    # ### end Alembic commands ###
