"""Updated migration for gamelogs

Revision ID: ac7972f7a8e3
Revises: c468a39d6816
Create Date: 2024-02-09 01:15:57.752062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7972f7a8e3'
down_revision = 'c468a39d6816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('game_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('matchup', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('wl', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('min', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fgm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fga', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fg_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fg3m', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fg3a', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fg3_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ftm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fta', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ft_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('oreb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dreb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reb', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ast', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stl', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tov', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pf', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plus_minus', sa.Integer(), nullable=True))
        batch_op.drop_constraint('game_log_season_stats_id_fkey', type_='foreignkey')
        batch_op.drop_column('assists')
        batch_op.drop_column('points')
        batch_op.drop_column('turnovers')
        batch_op.drop_column('season_stats_id')
        batch_op.drop_column('minutes_played')
        batch_op.drop_column('player_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('minutes_played', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('season_stats_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('turnovers', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('assists', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('game_log_season_stats_id_fkey', 'season_stats', ['season_stats_id'], ['id'])
        batch_op.drop_column('plus_minus')
        batch_op.drop_column('pts')
        batch_op.drop_column('pf')
        batch_op.drop_column('tov')
        batch_op.drop_column('blk')
        batch_op.drop_column('stl')
        batch_op.drop_column('ast')
        batch_op.drop_column('reb')
        batch_op.drop_column('dreb')
        batch_op.drop_column('oreb')
        batch_op.drop_column('ft_pct')
        batch_op.drop_column('fta')
        batch_op.drop_column('ftm')
        batch_op.drop_column('fg3_pct')
        batch_op.drop_column('fg3a')
        batch_op.drop_column('fg3m')
        batch_op.drop_column('fg_pct')
        batch_op.drop_column('fga')
        batch_op.drop_column('fgm')
        batch_op.drop_column('min')
        batch_op.drop_column('wl')
        batch_op.drop_column('matchup')
        batch_op.drop_column('game_id')
        batch_op.drop_column('season_id')

    # ### end Alembic commands ###
