"""Updated migration for gamelogs

Revision ID: d0cf1c4b971f
Revises: cc1cf02507ae
Create Date: 2024-02-10 02:55:36.955688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0cf1c4b971f'
down_revision = 'cc1cf02507ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=9), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('assist_leader', sa.Boolean(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('assists', sa.Float(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Float(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_stats_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('matchup', sa.String(), nullable=False),
    sa.Column('wl', sa.String(length=1), nullable=True),
    sa.Column('min', sa.Float(), nullable=False),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('fg3m', sa.Integer(), nullable=True),
    sa.Column('fg3a', sa.Integer(), nullable=True),
    sa.Column('fg3_pct', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Integer(), nullable=True),
    sa.Column('dreb', sa.Integer(), nullable=True),
    sa.Column('reb', sa.Integer(), nullable=True),
    sa.Column('ast', sa.Integer(), nullable=True),
    sa.Column('stl', sa.Integer(), nullable=True),
    sa.Column('blk', sa.Integer(), nullable=True),
    sa.Column('tov', sa.Integer(), nullable=True),
    sa.Column('pf', sa.Integer(), nullable=True),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_stats_id'], ['season_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_log')
    op.drop_table('season_stats')
    op.drop_table('season')
    op.drop_table('player')
    # ### end Alembic commands ###
