"""Updated migration for gamelogs

Revision ID: e9078df9813c
Revises: ac7972f7a8e3
Create Date: 2024-02-09 01:21:37.393302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9078df9813c'
down_revision = 'ac7972f7a8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_stats_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('game_log_player_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'season_stats', ['season_stats_id'], ['id'])
        batch_op.drop_column('season_id')
        batch_op.drop_column('player_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('season_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('game_log_player_id_fkey', 'player', ['player_id'], ['id'])
        batch_op.drop_column('season_stats_id')

    # ### end Alembic commands ###
